### ISSUE TITLE
issue with spark.yaml

### ISSUE THREAD

**Issue by gabrielpvbw** [Qualytics/qualytics-helm-public#3]
`gabriel@MacBook-Pro-2 ~/temp/qualytics-helm-public (main?) $ helm template --debug ./
install.go:194: [debug] Original chart version: ""
install.go:211: [debug] CHART PATH: /Users/gabrielvicente/temp/qualytics-helm-public

Error: parse error at (qualytics/templates/qualytics/spark.yaml:113): unexpected {{end}}
helm.go:84: [debug] parse error at (qualytics/templates/qualytics/spark.yaml:113): unexpected {{end}}`

**Comment by josecsotomorales** [comment]
Hi @gabrielpvbw! Will follow this up.
